# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.library.advice.thumbnail.folder.web: 'assets/library/advice'
    app.library.advice.thumbnail.folder.local: '%kernel.project_dir%/var/library/advice'

    app.layout.thumbnail.folder.web: 'assets/pages'
    app.layout.thumbnail.folder.local: '%kernel.project_dir%/var/pages'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Contracts\Library\Advice\PostThumbnailStorage:
        class: App\Service\Library\Advice\PostThumbnailStorage
        arguments:
            $rootPath: '%app.library.advice.thumbnail.folder.local%'

    App\Contracts\Layout\ThumbnailStorage:
        class: App\Service\Layout\PageThumbnailStorage
        arguments:
            $rootPath: '%app.layout.thumbnail.folder.local%'